### ISSUE TITLE
Support TexLive 2016

### ISSUE THREAD

**Issue by jfdm** [scottkosty/install-tl-ubuntu#24]
Not really an issue, more of a /in case you didn't know/. TexLive 2016 was released a few days ago. Time willing, I will try to see if I can do a PR and update the script to cater for it. 

Thanks for the script.

**Comment by scottkosty** [comment]
Thanks for opening this. I took a look and made one necessary change at f3def44. There's a chance that it works now but I'm going to avoid updating the docs to mention 2016 since I haven't had a chance to test.

**Comment by jfdm** [comment]
Just a quick reply, everything seems to have worked for me. Any problems, I shall report.

**Comment by scottkosty** [comment]
Sounds good, thanks for letting me know.
