### ISSUE TITLE
`Killed` when installing from iso on Vagrant vm

### ISSUE THREAD

**Issue by alagos** [scottkosty/install-tl-ubuntu#28]
I'm trying to install texlive on a vagrant vm (specifically [this Ubuntu 16.04 bento box](http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-16.04_chef-provisionerless.box)), but the script is simply failing when I try to use an iso image as source.
```
vagrant@vagrant:/vagrant$ sudo ./install-tl-ubuntu --iso iso/texlive2016-20160523.iso 
Killed
```

No log files were generated. Now if I run the script as default, there are no problems, but I really would like to avoid the pain to download every time the source.
```
vagrant@vagrant:/vagrant$ sudo ./install-tl-ubuntu 
install-tl-ubuntu: WARNING: this script currently supports Ubuntu 12.04, 12.10, 13.04, 13.10, and 14.04. 
For other versions, one would probably want to use a different 
debian-control-texlive-in.txt file.
install-tl-ubuntu: downloading the Debian control file...
--2016-09-20 21:03:05--  https://raw.github.com/scottkosty/install-tl-ubuntu/master/debian-control-texlive-in.txt
```

Running the same script file and using the iso as source, but on my own real Xubuntu 16.04 machine, is also working ok (at least in first glance) 
```
 ➜ sudo ./install-tl-ubuntu --iso iso/texlive2016-20160523.iso
install-tl-ubuntu: WARNING: this script currently supports Ubuntu 12.04, 12.10, 13.04, 13.10, and 14.04. 
For other versions, one would probably want to use a different 
debian-control-texlive-in.txt file.
install-tl-ubuntu: downloading the Debian control file...
--2016-09-20 18:11:09--  https://raw.github.com/scottkosty/install-tl-ubuntu/master/debian-control-texlive-in.txt
```

Any idea what could be wrong?

**Comment by scottkosty** [comment]
I have no idea why there is the difference. I would suggest putting `set -x` at the top of install-tl-ubuntu. This will turn on bash debugging and will hopefully give some more clues.

**Comment by alagos** [comment]
No idea what I did different, but now is working. Even I destroyed the vagrant vm and rebuilt it as I suppose it was yesterday, but it works. 
Closing in the meantime until me or someone else stumble upon this and could give more info.

**Comment by scottkosty** [comment]
I would still not be surprised if install-tl-ubuntu is to blame, so please let me know if you can reproduce it and have more information we can work off of.
