### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by Bisaloo** [scottkosty/install-tl-ubuntu#29]
You have been doing quite a lot of change since the last release (in 2014!) so you should probably program a new one.

Some people prefer downloading the tar.gz in the release section instead of cloning the git repo because release are supposed to be stable, which is not always the case for git repos.

**Comment by scottkosty** [comment]
Good points. Thanks for the idea. I will do that soon.

**Comment by scottkosty** [comment]
Fixed at a52a5a73.
