### ISSUE TITLE
404 on utexas.edu mirror

### ISSUE THREAD

**Issue by LieAlgebraCow** [scottkosty/install-tl-ubuntu#30]
When `./install-tl-ubuntu` is run, it does not finish.  The log file "install-tl-ubuntu_EXTRAS.log" is attached (changed to .txt).  The errors came after a 404 not found while trying to connect to "http://mirror.utexas.edu/ctan//install-tl-unx.tar.gz".

[install-tl-ubuntu_EXTRAS.txt](https://github.com/scottkosty/install-tl-ubuntu/files/547814/install-tl-ubuntu_EXTRAS.txt)

**Comment by scottkosty** [comment]
Thanks for opening this issue. Can you try specifying a different repository manually using the --repository option?

**Comment by LieAlgebraCow** [comment]
Sure.  Do you have an example of a repository I could use, or where to find one? I don't know any myself.

**Comment by scottkosty** [comment]
choose one that is geographically close to you from this list:
http://ctan.org/mirrors

**Comment by LieAlgebraCow** [comment]
Each of the following fails in the same way, with the same 404 error after attempting to connect to the mirror.utexas.edu domain.  Did I get something wrong?

`sudo ./install-tl-ubuntu --repository "ftp.math.purdue.edu"`
`sudo ./install-tl-ubuntu --repository "http://ftp.math.purdue.edu/mirrors/ctan.org/"`
`sudo ./install-tl-ubuntu --repository "http://mirror.ctan.org"`

**Comment by scottkosty** [comment]
I'm not sure what's going on. I hope I'll have time in the next days to take a deeper look. In the meantime, you could instead download the TeX Live iso and install from that. See the help output describing the `--iso` option for how to do this.

**Comment by LieAlgebraCow** [comment]
That didn't work either, so I suspect it might be an issue on my end. I managed to use the standard install-tl installer with the .iso, so I have TeX Live up and running now.  I'm going to close, because unless other people have this problem, it will be a better use of your time to work on other issues.  Thank you for your help.

**Comment by scottkosty** [comment]
Sorry we couldn't figure it out. I'd still like to figure out what's going on. What was the error you got when trying to using install-tl-ubuntu with the iso? I will make a virtual box install and see if I can reproduce somehow. I'm glad that you were able to install directly using install-tl.

**Comment by LieAlgebraCow** [comment]
When running `sudo ./install-tl-ubuntu --allow-small --iso ~/Downloads/texlive.iso`, I get the following output directly:

```
install-tl-ubuntu: checking for TeX Live environment variables...
install-tl-ubuntu: running apt and dpkg commands...
install-tl-ubuntu: apt-get cannot install parallel package to look for fastest mirror so we will use the default TeX Live repository.
install-tl-ubuntu: starting install-tl for time number 1...
install-tl-ubuntu: going to run the following command:
        echo "i" | "/media/tmp.SYo6WA7ZAy/install-tl" -v  -logfile "~/Downloads/install-tl-1.log"

install-tl-ubuntu: WARNING: ./install-tl failed.
install-tl-ubuntu: we will try to restart the install.
install-tl-ubuntu: starting install-tl for time number 2...
install-tl-ubuntu: going to run the following command:
        echo "i" | "/media/tmp.SYo6WA7ZAy/install-tl" -v  -logfile "~/Downloads/install-tl-2.log"
```

with the last five lines repeated until "time number 11", at which point I get

```
install-tl-ubuntu: WARNING: ./install-tl failed.

install-tl-ubuntu: ERROR: ./install-tl failed 11 times. Aborting.
```

The log file doesn't seem to have any useful error messaages, but it is attached anyway.
[install-tl-ubuntu_EXTRAS.txt](https://github.com/scottkosty/install-tl-ubuntu/files/573290/install-tl-ubuntu_EXTRAS.txt)

**Comment by scottkosty** [comment]
What is your distribution? I made a fix at 457198ee that might improve things for you. I would not be surprised if it does not fix this issue for you, but there is a chance. Can you please do a git pull and try again with the ISO? Thanks for your help with this.

**Comment by LieAlgebraCow** [comment]
The new version gave the same output as before.  I'm running Ubuntu 12.04 as chroot on ChromeOS, installed via Crouton.

**Comment by scottkosty** [comment]
Thanks for the details. I must have made a mistake in the commit, then. So to be sure, you still get 'apt-get cannot install parallel package' in the output, right?

**Comment by LieAlgebraCow** [comment]
Sorry, that line is gone.  The rest is the same though:

```install-tl-ubuntu: checking for TeX Live environment variables...
install-tl-ubuntu: running apt and dpkg commands...
install-tl-ubuntu: starting install-tl for time number 1...
install-tl-ubuntu: going to run the following command:
        echo "i" | "/media/tmp.4uzByVHvf5/install-tl" -v  -logfile "~/Downloads/install-tl-1.log"

install-tl-ubuntu: WARNING: ./install-tl failed.
install-tl-ubuntu: we will try to restart the install.
install-tl-ubuntu: starting install-tl for time number 2...
install-tl-ubuntu: going to run the following command:
        echo "i" | "/media/tmp.4uzByVHvf5/install-tl" -v  -logfile "~/Downloads/install-tl-2.log"
```

**Comment by scottkosty** [comment]
OK. What happens if you run the following command?

`echo "i" | "/media/tmp.4uzByVHvf5/install-tl" -v -logfile "~/Downloads/install-tl-1.log"`

**Comment by LieAlgebraCow** [comment]
Last night my chroot crashed and wouldn't restart, so I can't help any more with this issue:  I installed 14.04 trusty with crouton to start over, and now I'm getting `./install-tl-ubuntu: line 397: PARPREREQ: unbound variable`.  Should I open a new issue? Sorry I couldn't help you get this one worked out.

**Comment by scottkosty** [comment]
I will fix this now. This was a mistake I made in the previous commit. Should be fixed in 10 minutes. My apologies for the problems my script is causing you!

**Comment by scottkosty** [comment]
@LieAlgebraCow this should be fixed now at 0de081e. Can you confirm the problem is fixed now on your 14.04 install with the script? I added you to the AUTHORS file for your help with debugging. Thanks for your help and patience!

**Comment by LieAlgebraCow** [comment]
Same thing, but this time on line 396: `./install-tl-ubuntu: line 396: PARPREREQ: unbound variable`

**Comment by scottkosty** [comment]
My apologies. It should be fixed now at 8d1935e.

**Comment by LieAlgebraCow** [comment]
Yes, it starts the installation now without problems, although I didn't go through with the whole installation because I've already installed TeXLive otherwise.  It made it through the start of the apt commands, so all the issues I've been seeing are resolved.

**Comment by scottkosty** [comment]
@LieAlgebraCow thanks for your help in testing that.
