### ISSUE TITLE
'\r': command not found

### ISSUE THREAD

**Issue by bisraelsen** [scottkosty/install-tl-ubuntu#32]
Running a fresh clone of the repo. Getting the following errors when executing `./install-tl-ubuntu`

```
./install-tl-ubuntu: line 2: $'\r': command not found
./install-tl-ubuntu: line 3: $'\r': command not found
./install-tl-ubuntu: line 5: $'\r': command not found
./install-tl-ubuntu: line 8: $'\r': command not found
./install-tl-ubuntu: line 9: $'\r': command not found
./install-tl-ubuntu: line 11: $'\r': command not found
./install-tl-ubuntu: line 24: $'\r': command not found
./install-tl-ubuntu: line 25: $'\r': command not found
: invalid option nameline 26: set: nounset
./install-tl-ubuntu: line 27: $'\r': command not found
./install-tl-ubuntu: line 28: syntax error near unexpected token `$'\r''
'/install-tl-ubuntu: line 28: `function clean_up ()
```

**Comment by bisraelsen** [comment]
Admittedly this is an extreme measure, but I had been having a few other quirky problems so I reinstalled the Windows Linux subsystem and now it `install-tl-ubuntu` works like a charm!

Of course, I don't understand the reason why the error was caused, but the problem is solved.

**Comment by scottkosty** [comment]
@bisraelsen thanks for reporting this. Something must have been wrong with interpreting line endings.

It is the first time I have heard of `install-tl-ubuntu` being used on the Windows Linux subsystem. Were any other changes needed?

**Comment by bisraelsen** [comment]
No changes were needed. I may have had an older version on this computer (that is my hypothesis given that reinstalling seemed to fix the problem). My other PC worked flawlessly the first time I used `install-tl-ubuntu` on it.

**Comment by scottkosty** [comment]
Good, thanks for the confirmation!
