### ISSUE TITLE
TeX Live 2017 has been released

### ISSUE THREAD

**Issue by mathuin** [scottkosty/install-tl-ubuntu#36]
https://www.tug.org/texlive/acquire.html

TeX Live 2017 was released today.

**Comment by o9o** [comment]
I've noticed that the script downloads the latest distribution without any change.

**Comment by mathuin** [comment]
Just ran the script today, this was the output:

```
install-tl-ubuntu: WARNING: this script currently supports Ubuntu 12.04, 12.10, 13.04, 13.10, and 14.04. 
For other versions, one would probably want to use a different 
debian-control-texlive-in.txt file.
install-tl-ubuntu: checking for TeX Live environment variables...
sudo: unknown user: nala-local:x:1000:1000:nala-local,,,:/localhome/nala-local:/bin/bash
sudo: unable to initialize policy plugin
install-tl-ubuntu: running apt and dpkg commands...
install-tl-ubuntu: determining the fastest repository...
install-tl-ubuntu: the fastest repo is: http://muug.ca/mirror/ctan
install-tl-ubuntu: downloading and extracting install-tl for time number 1...
install-tl-ubuntu: install-tl downloaded and extracted successfully.
install-tl-ubuntu: starting install-tl for time number 1...
install-tl-ubuntu: going to run the following command:
        echo "i" | ./install-tl -repository "http://muug.ca/mirror/ctan/systems/texlive/tlnet/" -v  -logfile "/home/jmt/git/install-tl-ubuntu/install-tl-1.log"

install-tl-ubuntu: WARNING: ./install-tl failed.
install-tl-ubuntu: the installer and repo are mismatched. 
For example, the installer could be for TeX Live 2015 and the repo for 2014.
```

**Comment by o9o** [comment]
For me it worked with:

```
./install-tl-ubuntu -q http://mirror.switch.ch/ftp/mirror/tex/systems/texlive/tlnet/
```
Maybe your mirror is not in a consistent state?

I've also removed my `/usr/local/texlive` first, and the script was executed from a clean clone. I'm not sure if it tries to cache anything.

The I see the correct version:

```
$ pdflatex -v
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017)
kpathsea version 6.2.3
Copyright 2017 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.29; using libpng 1.6.29
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 3.04
```

**Comment by mathuin** [comment]
I recently had a change to nuke my entire TeX setup on my system and rebuild from scratch.  It does build with TeX Live 2017 now.  No need for this issue!

**Comment by scottkosty** [comment]
@mathuin I'm glad it worked! Thanks for updating the thread.

**Comment by AlfonsoMuskedunder** [comment]
@scottkosty Wouldn't the release of TeX Live 2018 be an excellent reason to overhaul the script a little bit...? :wink:

_P.S. Thank you for providing it in the first place, it has helped me a lot in the past!_ :clap:

**Comment by scottkosty** [comment]
@AlfonsoMuskedunder it would indeed :) Thank you for this gentle push. I am planning to look into it in the next month or so.

**Comment by AlfonsoMuskedunder** [comment]
Hi, just a quick question...

I just ran the script in order to install TeX Live 2018, and it mostly succeeded, with one little exception: There was one warning which I unfortunately forgot to record before rebooting, I think it said that one particular file could not be created because it already existed, possibly a symbolic link?

Well, now when I run `pdftex -v` I still see `pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017)`, but when I run `/opt/texbin$ ./pdftex -v` I get `pdfTeX 3.14159265-2.6-1.40.19 (TeX Live 2018)`.

I tried to look up my `PATH` in `/etc/environment`, and it includes `PATH="/opt/texbin:/usr/local/sbin ...`.

Can anyone tell me how I can point my system to TL 2018...?

**Comment by scottkosty** [comment]
@AlfonsoMuskedunder what is the output of `which -a pdftex` ?

**Comment by AlfonsoMuskedunder** [comment]
It is
```
/usr/local/texlive/2017/bin/x86_64-linux/pdftex
/opt/texbin/pdftex
```

**Comment by scottkosty** [comment]
@AlfonsoMuskedunder you could either remove `/usr/local/texlive/2017/` from your path, or make sure that  `/opt/texbin/pdftex` comes first in your path.

**Comment by AlfonsoMuskedunder** [comment]
Sorry for hijacking this thread again, but today I tried to run the script to install TL 2019. The log file says

> ./install-tl: The TeX Live versions of the local installation
> and the repository being accessed are not compatible:
>       local: 2018
>  repository: 2019
> Perhaps you need to use a different CTAN mirror?

Like in the [comment above](https://github.com/scottkosty/install-tl-ubuntu/issues/36#issuecomment-309537107), I emptied `/usr/local/texlive/` before running the script as well, but with the same effect.

Any help would be appreciated.

**Comment by scottkosty** [comment]
@AlfonsoMuskedunder how did you solve the problem last time?

**Comment by AlfonsoMuskedunder** [comment]
I think last time and now are different problems: Last time the installation as such succeeded, but the PATH variable still pointed to the old installation. (BTW, I followed your advice and removed `/usr/local/texlive/2017/` from PATH; sorry for not reporting back. Thanks again!)

This time, the script won't run. This is the complete output:
```
install-tl-ubuntu: checking for TeX Live environment variables...
install-tl-ubuntu: running apt and dpkg commands...
install-tl-ubuntu: determining the fastest repository...
install-tl-ubuntu: the fastest repo is: http://vesta.informatik.rwth-aachen.de/ftp/pub/mirror/ctan
install-tl-ubuntu: downloading and extracting install-tl for time number 1...
install-tl-ubuntu: install-tl downloaded and extracted successfully.
install-tl-ubuntu: starting install-tl for time number 1...
install-tl-ubuntu: going to run the following command:
        echo "i" | ./install-tl -repository "http://vesta.informatik.rwth-aachen.de/ftp/pub/mirror/ctan/systems/texlive/tlnet/" -v  -logfile "/home/thorsten/GitHub/install-tl-ubuntu/install-tl-1.log"

install-tl-ubuntu: WARNING: ./install-tl failed.
install-tl-ubuntu: the installer and repo are mismatched. 
For example, the installer could be for TeX Live 2015 and the repo for 2014.
```

**Comment by scottkosty** [comment]
@AlfonsoMuskedunder could you try running install-tl-ubuntu with the option `--repository` and choose a different repository?

**Comment by AlfonsoMuskedunder** [comment]
I tried 5 different repos - the effect was the same each time... For instance:
```
...
install-tl-ubuntu: going to run the following command:
        echo "i" | ./install-tl -repository "ftp://archive.cs.uu.nl/mirror/CTAN/systems/texlive/tlnet/" -v  -logfile "/home/alfonso/GitHub/install-tl-ubuntu/install-tl-1.log"

install-tl-ubuntu: WARNING: ./install-tl failed.
install-tl-ubuntu: the installer and repo are mismatched.
...
```

**Comment by scottkosty** [comment]
@AlfonsoMuskedunder Dang it that's strange. I am traveling now but if you ping me in 1 month I can try to reproduce on a virtual box instance. Unless I can reproduce, I'm not sure what else to try. Maybe post the full command that you're trying and the full output of the command and the log file(s).

**Comment by AlfonsoMuskedunder** [comment]
Thank you. For future efforts, here's the terminal output:
```
alfonson@alfonso:~/GitHub/install-tl-ubuntu$ sudo ./install-tl-ubuntu
install-tl-ubuntu: checking for TeX Live environment variables...
install-tl-ubuntu: running apt and dpkg commands...
install-tl-ubuntu: determining the fastest repository...
install-tl-ubuntu: the fastest repo is: http://vesta.informatik.rwth-aachen.de/ftp/pub/mirror/ctan
install-tl-ubuntu: downloading and extracting install-tl for time number 1...
install-tl-ubuntu: install-tl downloaded and extracted successfully.
install-tl-ubuntu: starting install-tl for time number 1...
install-tl-ubuntu: going to run the following command:
        echo "i" | ./install-tl -repository "http://vesta.informatik.rwth-aachen.de/ftp/pub/mirror/ctan/systems/texlive/tlnet/" -v  -logfile "/home/alfonso/GitHub/install-tl-ubuntu/install-tl-1.log"

install-tl-ubuntu: WARNING: ./install-tl failed.
install-tl-ubuntu: the installer and repo are mismatched. 
For example, the installer could be for TeX Live 2015 and the repo for 2014.
```
A gist of the standard log file [can be found here](https://gist.github.com/AlfonsoMuskedunder/088d2a18076b4ceffd5ecc3b15310c17).
A gist of install-tl-ubuntu_EXTRAS.log [is here](https://gist.github.com/AlfonsoMuskedunder/7c3738d09df404ef59165375f2afe423).

**Comment by scottkosty** [comment]
@AlfonsoMuskedunder  Thanks for posting those. Unfortunately, I couldn't figure it out. Ping me in a month and I can try in a virtual box. Perhaps I hardcoded a URL to the installer and that URL is out of date.

**Comment by AlfonsoMuskedunder** [comment]
Hi @scottkosty, consider this a ping! :bell: I just tried once more and I still get the same errors.

**Comment by scottkosty** [comment]
@AlfonsoMuskedunder thanks for the ping. One option is to try the DVD iso. See the documentation from `install-tl-ubuntu --help` regarding the `--iso` option.

**Comment by AlfonsoMuskedunder** [comment]
Thank you, using the ISO worked out fine!

**Comment by scottkosty** [comment]
> Thank you, using the ISO worked out fine!

That's great! I still wish we could figure out your original issue, but I'm happy that you've got at least a temporary solution. Can you use tlmgr to update after installing from the ISO?

**Comment by AlfonsoMuskedunder** [comment]
> That's great! I still wish we could figure out your original issue, but I'm happy that you've got at least a temporary solution.

Yeah, I'm surprised that I appear to be the only one having experienced this.

> Can you use tlmgr to update after installing from the ISO?

Yup, it worked instantly! I had expected that I might have to change repos with `tlmgr option repository ctan` or so, but no need for that.

**Comment by scottkosty** [comment]
> Yup, it worked instantly! I had expected that I might have to change repos with `tlmgr option repository ctan` or so, but no need for that.

Great! Thanks for those details, that's good to know.

**Comment by bisraelsen** [comment]
I'm having the same problem... not sure what's happening

**Comment by scottkosty** [comment]
@bisraelsen thanks for the update, glad it seems to be working (at least for now)!
