### ISSUE TITLE
This doesn't seem to run at all when used as part of a github action in a slim Docker image

### ISSUE THREAD

**Issue by Pomax** [scottkosty/install-tl-ubuntu#37]
Action code:
```
      - name: Installing TeX Live
        run: |
          apt-get update
          wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu
          chmod +x ./install-tl-ubuntu
          ./install-tl-ubuntu
          tlmgr --version
```
Which should, reasonably speaking, just work. Instead it does this:
```
| --2020-06-07 18:57:18--  https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu
| Resolving github.com (github.com)... 140.82.113.3
| Connecting to github.com (github.com)|140.82.113.3|:443... connected.
| HTTP request sent, awaiting response... 302 Found
| Location: https://raw.githubusercontent.com/scottkosty/install-tl-ubuntu/master/install-tl-ubuntu [following]
| --2020-06-07 18:57:18--  https://raw.githubusercontent.com/scottkosty/install-tl-ubuntu/master/install-tl-ubuntu
| Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.52.133
| Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.52.133|:443... connected.
| HTTP request sent, awaiting response... 200 OK
| Length: 36820 (36K) [text/plain]
| Saving to: 'install-tl-ubuntu.2'
|
install-tl-ubuntu.2 100%! (BADINDEX) 35.96K  --.-KB/s    in 0.02s
|
| 2020-06-07 18:57:19 (2.09 MB/s) - 'install-tl-ubuntu.2' saved [36820/36820]
|
| ./install-tl-ubuntu: line 356: lsb_release: command not found
| install-tl-ubuntu: checking for TeX Live environment variables...
| ./install-tl-ubuntu: line 299: sudo: command not found
| install-tl-ubuntu: running apt and dpkg commands...
```

At the very least this should be able to run without `sudo` if it's already running with superuser permissions.

**Comment by scottkosty** [comment]
I don't think I'll be much help here so I don't have experience with GitHub actions. As for the first error, it seems that it can't find the command `lsb_release`. Why would that be? That command should be available on all versions of Ubuntu as far as I know.

What version of Ubuntu is this?

**Comment by Pomax** [comment]
for normal OS, sure - but not in slim Docker linux images. Heck, this particular one (used by [act](https://github.com/nektos/act), which lets you test github actions locally) doesn't even have `sudo` (which is the second error).

**Comment by scottkosty** [comment]
This seems outside the scope of install-tl-ubuntu. Even dealing with the particularities of different Ubuntu versions can be complicated at times. I do not think I will have time to look into this fixing this issue myself. Are you interested in making a pull request? I would prefer to not make too many special cases in the code, so we should discuss a plan beforehand. Does that docker image even use apt as the package management? I'm guessing that the specific issues (sudo and lsb_release) are the least of the concerns and there will be many complications. But if you are very motivated, we can discuss further.

Regarding sudo, I agree that if it is run as super user the sudo calls could be avoided. On a related but different topic, it would be nice if `install-tl-ubuntu` had an option to not require sudo or super user privileges at all (i.e., allow for an installation for the single user, not system-wide).

**Comment by Pomax** [comment]
fair enough.
