### ISSUE TITLE
TeX Live years in README.md seem to confuse users

### ISSUE THREAD

**Issue by cabohah** [scottkosty/install-tl-ubuntu#42]
It seems that the “as of writing, **TeX Live 2019**” in the **Features** section of the [README.md](https://github.com/scottkosty/install-tl-ubuntu#readme) and the two “TeX Live 2016 installer” in the **Description** section confuse some users. They think, the script is still either for TeX Live 2019 or TeX Live 2016 only. See e.g. pglpm's comments to [this question at TeX.Stackexchange](https://tex.stackexchange.com/q/689177/277964). So maybe it would be a good idea to remove the “as of writing” note and reduce the other to “TeX Live installer” or “TeX Live installer (latest version)”.

**Comment by scottkosty** [comment]
Thanks for these suggestions! I'll take a look soon.

**Comment by scottkosty** [comment]
@cabohah The previous text was definitely confusing. Thank you!

**Comment by ofenerci** [comment]
Is there an option to set up small texlive environment?

**Comment by scottkosty** [comment]
> Is there an option to set up small texlive environment?

Yes, you can use the "--profile" option. You can copy the "example.profile" file in this repository and edit accordingly and then pass it to the "--profile" option.

Alternatively, you might consider TinyTeX. I don't know anything about it but it sounds pretty interesting: https://yihui.org/tinytex/. If you happen to use R, you can even install a minimal TeX installation with a couple commands of R: https://cran.r-project.org/web/packages/tinytex/index.html

**Comment by cabohah** [comment]
> Yes, you can use the "--profile" option. You can copy the "example.profile" file in this repository and edit accordingly and then pass it to the "--profile" option.

TeX Live provides several schemes, e.g.:

* `scheme-infraonly`: no TeX or LaTeX or ConTeXt only the infrastructure of TeX Live
* `scheme-minimal`: like `scheme-infraonly` but with (plain)TeX
* `scheme-basic`: like `scheme-minimal` but with LaTeX, only basic packages
* `scheme-small`: like `scheme-basic` with more packages, XeTeX, MetaPost and some languages
* `scheme-medium`: like `scheme-small` but with extra packages and languages
* `scheme-full`: the full TeX Live with (almost) all packages (this is the default)

There are some more schemes, but usually you want one of the above. But note, that you not only have to change the `selected_scheme scheme-full` line in the `example.profile`, but also the collection list. Sorry, but I don't know, whether or not the collection list is really needed. Maybe it would be enough to only select a scheme.

BTW: IMHO this is a completely new question unrelated to the (already solved) issue of this report. I usually recommend, to ask such questions either in a forum like TeX.SX or in a separate issue.
