### ISSUE TITLE
The output of the --help option is out-of-date

### ISSUE THREAD

**Issue by ttmc** [scottkosty/install-tl-ubuntu#45]
Today, when you do `./install-tl-ubuntu --help`, the description section begins with:

```
DESCRIPTION
  This script uses the TeX Live 2016 installer to install TeX Live so that LaTeX
  packages can be updated through CTAN with tlmgr. To do this, the official TeX
  Live 2016 installer is downloaded...
```

but that description is out-of-sync with the `README.md` file which says:

## Features

- installs the latest version of TeX Live
- etc.

**Comment by scottkosty** [comment]
Nice catch, thank you! I fixed the year issue. I don't think I want to add the features to '--help'. I think it's fine to leave that part out-of-sync with the README.
